<?php
// $Id$

function forum_readall_menu($may_cache) {
  $items = array();
  if ($may_cache) {
    $items[] = array(
      'path' => 'forum/readall',
      'callback' => 'forum_readall_read',
      'access' => user_access('access content'),
      'type' => MENU_LOCAL_TASK,
    );
  }
  return $items;
}


function forum_readall_read($tid = 0) {
  global $user;
  if ($user && $user->uid)  {
    if (is_numeric($tid) && $tid)  {
      $sql = "REPLACE INTO {history} (uid, nid, timestamp) 
              SELECT %d, n.nid, UNIX_TIMESTAMP() from {node} n 
              INNER JOIN {term_node} r ON n.nid = r.nid 
              INNER JOIN {node_comment_statistics} l ON l.nid = n.nid 
              WHERE (n.created > %d OR l.last_comment_timestamp > %d) AND r.tid = %d";
      db_query($sql, $user->uid, NODE_NEW_LIMIT, NODE_NEW_LIMIT, $tid);
      drupal_set_message(t('All posts in the selected forum have been marked as read'));
      drupal_goto("forum/$tid");
    } 
    else {
      $sql = "REPLACE INTO {history} (uid, nid, timestamp) 
              SELECT %d, n.nid, UNIX_TIMESTAMP() from {node} n 
              INNER JOIN {node_comment_statistics} l ON l.nid = n.nid 
              WHERE (n.created > %d OR l.last_comment_timestamp > %d)";
      db_query($sql, $user->uid, NODE_NEW_LIMIT, NODE_NEW_LIMIT);
      drupal_set_message(t('All posts in all forums have been marked as read'));
      drupal_goto("forum");
    }
  }
}

